### ISSUE TITLE
Setup Folding@Home on single EC2 instance

### ISSUE THREAD

**Issue by steinbachr** [MeanPug/folding-together#1]
**Helpful Links:**

* https://foldingathome.org/support/faq/installation-guides/linux/command-line-options/
* https://foldingathome.org/support/faq/installation-guides/linux/manual-installation-advanced/

**Goal**
To get the folding@home software set up and working on a single EC2 tiny instance. Documentation of any issues / steps can be attached as comments

**Comment by atkinsonm** [comment]
For reference: https://github.com/jkataja/cfn-foldingathome

**Comment by atkinsonm** [comment]
Current plan: create one instance for each donor and run it as long as funds remain.

Open implementation choice on using CloudFormation or EC2 APIs directly.

**Comment by atkinsonm** [comment]
Using existing CloudFormation template is probably going to be the quickest solution as long as parameters can be adjusted for running one instance per stack which is specific to one donor, and as long as there are no other implications of using CloudFormation (cot, performance, operations, etc.). No other implications are anticipated other than #17

**Comment by steinbachr** [comment]
template located @ s3://folding-together-artifacts/cloudformation/foldingathome.yaml
