### ISSUE TITLE
Allow donor to specify a team

### ISSUE THREAD

**Issue by atkinsonm** [MeanPug/folding-together#18]
Currently we default to no team. A donor should be able to specify a team.

The donor-team combo can be a unique value in the balance tracker.

**Comment by steinbachr** [comment]
im gonna close this out, because I've actually created a custom team for our org (team name `Folding@Together`, id=255839) in order to track combined stats

**Comment by atkinsonm** [comment]
Yep, I prefer the one team for combined stats
