### ISSUE TITLE
Determine scheduler run frequency

### ISSUE THREAD

**Issue by atkinsonm** [MeanPug/folding-together#26]
Pick a frequency and write a cron expression for it in a CloudWatch event that can be used for the state machine trigger

**Comment by atkinsonm** [comment]
Make sure to also adjust in the [lookup_instance_cost function](https://github.com/MeanPug/folding-together/blob/master/lambda/lookup_instance_cost/lookup_instance_cost.py#L5)

**Comment by steinbachr** [comment]
done (running every 5 minutes)
