### ISSUE TITLE
Create registration and payment gateway

### ISSUE THREAD

**Issue by steinbachr** [MeanPug/folding-together#4]
The gateway simply needs to allow for basic user registration and payments. Upon successful payment, it can queue a task to schedule compute for the available credits.

**Comment by atkinsonm** [comment]
What's your experience in integrating with payment apps? I'd rather not process payment info if I can avoid it for obvious security reasons.

**Comment by atkinsonm** [comment]
Separate to the payment portal, perhaps we can take donations of AWS promo codes and manually apply them (since there's no API for that). Just another avenue to accept donations.

**Comment by steinbachr** [comment]
i've never really had a problem, security or otherwise, with Stripe integration. Especially given these are small donations ($1-$10), I'm not too worried about it...that said, love the promo code thought

**Comment by steinbachr** [comment]
also makes sense to reach out directly to AWS to see if they'll offer free credits for the cause

**Comment by steinbachr** [comment]
once we have the scheduler in place, i think we can revisit ways to load up on balance

**Comment by atkinsonm** [comment]
My two cents: static S3 bucket website for the payment portal could be easiest to set up and maintain, if viable

**Comment by steinbachr** [comment]
would definitely be the cheapest, but it would mean decoupling the landing page from payment/registration (since for Stripe you need to maintain a secret token server-side)..I'm probably just going to throw them all together in a Django app and call it a day tbh

**Comment by steinbachr** [comment]
todos:

- [x] create necessary models
- [ ] create registration and donation pages
- [ ] publish sqs message on donation
